### ISSUE TITLE
Reconnect on timeout (Ethernet gateway)

### ISSUE THREAD

**Issue by danylevskyi** [rakeshpai/mysensors-controller#1]
First of all, I'd like to thank you for the project! It's great!

I've found a problem using Ethernet gateway. The controller will not reconnect if there is a problem with a connection to the gateway. `error` event is not emitted as expected.
### How to reproduce

```
require("mysensors-controller");
var controller = mysensors.usingEthernetGateway('192.168.1.66', '5003');

// We assume here that the gateway emits new messages every 3 seconds.
controller.on('sensorUpdate', function () {
  console.log('data...');
});
```
1. Run the program and you'll see `data...` message every 3 seconds.
2. Switch off the gateway or unplug ethernet wire.
3. You'll see that the controller is just stacked.
### Expected behavior

The controller should try to reconnect if there is a problem with the connection.

I'll provide a pull request to fix this problem.

**Comment by rakeshpai** [comment]
Merged from https://github.com/rakeshpai/mysensors-controller/pull/2 Thanks, @danylevskyi!
